### ISSUE TITLE
chp1 分支上的 rustsbi 版本不能支持 shutdown 

### ISSUE THREAD

**Issue by LimingFang** [rcore-os/rCore-Tutorial-v3#127]
目前 chp1 上是直接使用 sbi-rt 完成的关机，但是教学文档里是自己定义 rustsbi 函数实现 shutdown 功能：
![image](https://github.com/rcore-os/rCore-Tutorial-v3/assets/28479651/43583dc6-ba5a-41a5-9691-7a58b1dfe191)
但是估计是 chp1 附带的 rustsbi 版本不对，ecall 后没有正常关机

**Comment by wyfcyx** [comment]
现在仓库里面的rustsbi对齐到sbi spec 1.0以上版本，其中shutdown作为legacy接口，rustsbi已经不支持了，而是用system reset拓展来实现同样的功能。近几天我会更新一下文档。
