### ISSUE TITLE
Cargo.toml 里面作者 吴亦凡 名称是否考虑移除呢？

### ISSUE THREAD

**Issue by bluetianx** [rcore-os/rCore-Tutorial-v3#24]
cargo toml 文件里面有关于吴亦凡的著名，是否考虑移除？

```
[package]
name = "os"
version = "0.1.0"
authors = ["Yifan Wu <shinbokuow@163.com>"]
edition = "2018"
```

**Comment by jiegec** [comment]
您好，这位同学的姓名拼音虽然是 Yifan Wu，但并不是 吴亦凡 这三个字，只是读音相近。

**Comment by Harry-Chen** [comment]
就算是同名的同学，你又有什么立场要求移除他呢？

**Comment by KireinaHoro** [comment]
巧了，本人也認識好幾個 Yifan Wu

**Comment by bluetianx** [comment]
> 就算是同名的同学，你又有什么立场要求移除他呢？

我以为是吴亦凡而已，我issue上面写的 是否考虑 ，并没有说一定要移除

**Comment by bluetianx** [comment]
@wyfcyx  十分抱歉，这是一个误会，另外非常感谢你对这个项目的付出。

**Comment by Harry-Chen** [comment]
> > 就算是同名的同学，你又有什么立场要求移除他呢？
> 
> 我以为是吴亦凡而已，我issue上面写的 是否考虑 ，并没有说一定要移除

不明白为什么会对一个开源项目有这样的想法，请不要把微博那一套乌烟瘴气带到 GitHub 上来。

**Comment by PanQL** [comment]
拼音Yifan Wu的招你惹你了（笑哭.jpg）
