### ISSUE TITLE
能请教下qemu 使用的bootloader是怎么制作的吗？谢谢

### ISSUE THREAD

**Issue by techzealot** [rcore-os/rCore-Tutorial-v3#30]

**Comment by wyfcyx** [comment]
这个说起来比较复杂，如果有兴趣了解的话，可以参考[rustsbi](https://github.com/rustsbi/rustsbi)和[rustsbi-qemu](https://github.com/rustsbi/rustsbi-qemu)，我们的项目直接使用了它们来作为bootloader。

**Comment by techzealot** [comment]
> 这个说起来比较复杂，如果有兴趣了解的话，可以参考[rustsbi](https://github.com/rustsbi/rustsbi)和[rustsbi-qemu](https://github.com/rustsbi/rustsbi-qemu)，我们的项目直接使用了它们来作为bootloader。

非常感谢，找了半天没看到生成bootloader的地方，原来如此
