### ISSUE TITLE
ch2练习求教

### ISSUE THREAD

**Issue by csyJoy** [rcore-os/rCore-Tutorial-v3#32]
题目要求检查sys_write的访问物理地址合法性，在检查02power的物理地址的时候发现所有数字的物理地址都在内核的rodata段内，请问这是为什么？
![image](https://user-images.githubusercontent.com/58020450/136666365-d662edbd-6404-4a62-9bcd-d24af5f8ef84.png)
如图所示，当OS在打印3的时候，指针指向了kernel的.rodata段。

**Comment by LimingFang** [comment]
我也发现了这个问题。
直接略微修改本repo `ch2` 分支，在用户的 `main` 中 `println!("{}",1)` ，然后在 `fs.rs` 中会发现传进来的缓冲区起始地址在 0x8020_0000上一点（理论上应该是0x8040_0000上一点）
