### ISSUE TITLE
failed to load source for dependency `k210-hal`

### ISSUE THREAD

**Issue by harjim** [rcore-os/rCore-Tutorial-v3#44]
![image](https://user-images.githubusercontent.com/80667818/145976810-75246e14-6a73-40d7-9345-471da66d1b18.png)

`make run` 报这个错，查阅资料没发现有什么好方法，请问可以怎么解决呢。

**Comment by wyfcyx** [comment]
这个应该是由于网络问题，目前除了科学上网之外似乎没有更好的解决办法。

**Comment by harjim** [comment]
可我 rust 镜像配置的已经是国内镜像了，梯子也开着的。其它的包下载好像也没问题。

**Comment by harjim** [comment]
![image](https://user-images.githubusercontent.com/80667818/146104643-3b7816d5-c49f-4c99-bae6-b161b3530e52.png)

注意到报错信息有提到一个 config 配置，查阅官网文档 https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli 后，可能是 cargo 下载 git 库会有一些问题？

在添加配置之后运行 `make run` 成功编译。具体问题的原因与该配置项解决了什么还没搞明白。

**Comment by Paul-bl** [comment]
具体是怎么配置的呢
