### ISSUE TITLE
make run 出错

### ISSUE THREAD

**Issue by sTallone777** [rcore-os/rCore-Tutorial-v3#51]
Last week I checked out the main branch and run "make run", ererything was fine.

Today I checked out the lastest min branch and run "make run", there is a panic happend:
![屏幕截图 2022-01-26 114033](https://user-images.githubusercontent.com/45021798/151094930-b61b4444-32f2-41e4-9c93-9723b911aafc.jpg)

Is there something I missed?

**Comment by wyfcyx** [comment]
This is because I forgot to merge recent updates to the main branch. Now you can pull and try again.
