### ISSUE TITLE
make run: Blocking waiting for file lock on package cache

### ISSUE THREAD

**Issue by Yang-Xijie** [rcore-os/rCore-Tutorial-v3#53]
<img width="798" alt="image" src="https://user-images.githubusercontent.com/57952362/152470362-e4baa3a0-0f1a-4485-81bd-8b86d0e6f4f1.png">

在macOS上直接运行ch2的代码产生上面的报错，然后就卡住了。请问这是什么问题呢？

**Comment by liy010** [comment]
有其他程序在更新包吧

**Comment by Yang-Xijie** [comment]
不知道发生了什么又好了
貌似是VSCode的Rust插件
