### ISSUE TITLE
llvm_asm切换到asm引发的报错

### ISSUE THREAD

**Issue by OverrideRe** [rcore-os/rCore-Tutorial-v3#57]
您好，目前我现在在坐第四章的练习，在运行ch4分支的时候报找不到asm!的错误

<img width="813" alt="image" src="https://user-images.githubusercontent.com/20578246/154985354-ea53b6ec-8069-48c3-90e2-a668905cb1ce.png">

我想可能是因为nightly版本过低（ch4分支里的版本是nightly-2021-01-30），所以我更新为nightly-2021-10-15，现在是不报找不到asm!的错误了，可是又报使用不稳定版本的特性asm，明明我配置的工具链是nightly版本的。

<img width="868" alt="image" src="https://user-images.githubusercontent.com/20578246/154984287-8c54b62a-f45f-4a41-9dff-2631d0df0ab1.png">

main分支也是报这个错

<img width="868" alt="image" src="https://user-images.githubusercontent.com/20578246/154985714-440a2a22-2f0b-4bc3-8e8b-acb3f63ac0e6.png">

报错的地方是项目引用riscv中的一个模块，应该是这个修改：https://github.com/rcore-os/riscv/commit/11d43cf7cccb3b62a3caaf3e07a1db7449588f9a

系统版本是CentOS Linux release 7.6.1810

我需要怎么做才能正常运行啊

**Comment by wyfcyx** [comment]
请通过`git pull`更新本地的ch4分支。

**Comment by yfblock** [comment]
报错下方已经给出了建议解决方案&nbsp; 添加#![feature(asm)]


或者将rust更新到最新版本&nbsp; 最新版本已经将asm stable了
 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月21日 23:37:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [rcore-os/rCore-Tutorial-v3] llvm_asm切换到asm引发的报错 (Issue #57)




 
您好，目前我现在在坐第四章的练习，在运行ch4分支的时候报找不到asm!的错误
 

 
我想可能是因为nightly版本过低（ch4分支里的版本是nightly-2021-01-30），所以我更新为nightly-2021-10-15，现在是不报找不到asm!的错误了，可是又报使用不稳定版本的特性asm，明明我配置的工具链是nightly版本的。
 

 
main分支也是报这个错
 

 
***@***.***
 
系统版本是CentOS Linux release 7.6.1810
 
我需要怎么做才能正常运行啊
