### ISSUE TITLE
docker中，在os中make run会出现以下错误

### ISSUE THREAD

**Issue by E-Jaeger** [rcore-os/rCore-Tutorial-v3#63]
docker中，在os中make run会出现以下错误
<img width="721" alt="截屏2022-04-01 下午6 17 43" src="https://user-images.githubusercontent.com/81407594/161244676-31ea99ba-470c-49b6-9cf8-b5f775d10834.png">

**Comment by chyyuu** [comment]
谢谢！应该已经fix了。
