### ISSUE TITLE
疑问，第一章中实践篇的每两指令地址相差为什么不是8

### ISSUE THREAD

**Issue by pzzxqj** [rcore-os/rCore-Tutorial-v3#96]
> ```shell
> (gdb) x/10i $pc
> => 0x1000:  auipc   t0,0x0
> 0x1004:     addi    a1,t0,32
> 0x1008:     csrr    a0,mhartid
> 0x100c:     ld      t0,24(t0)
> 0x1010:     jr      t0
> 0x1014:     unimp
> 0x1016:     unimp
> 0x1018:     unimp
> 0x101a:     0x8000
> 0x101c:     unimp
> ```
这段内容来自 http://rcore-os.cn/rCore-Tutorial-Book-v3/chapter1/4first-instruction-in-kernel2.html#gdb

riscv64的每条指令都是64位，于是每条指令指令相差8个字节即64位。为什么教材和实际调式中看到的是相差4个字节？我遗漏了什么？

**Comment by wyfcyx** [comment]
rv64的位宽是64位，指的是通用寄存器（以及其他某些寄存器）还有指针的位宽，这和指令的位宽没有必然联系。rv64上指令位宽一般为32位也即4字节，启用C拓展之后某些指令甚至会被压缩为2字节。在x86这种平台上则是变长指令，就是说不同指令的位宽可能不同。
